version: "3.8"

services:
  mysql-docker:
    image: mysql:8.0
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ginchat
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ginchat_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 10

  my-redis:
    image: redis:7.2
    container_name: my-redis
    restart: always
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6379:6379"
    networks:
      - ginchat_net

  ginchat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ginchat-ginchat-app
    restart: always
    depends_on:
      mysql-docker:
        condition: service_healthy
      my-redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql-docker
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: ginchat
      REDIS_HOST: my-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
    networks:
      - ginchat_net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    restart: always
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /etc/localtime:/etc/localtime:ro
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    networks:
      - ginchat_net

volumes:
  mysql-data:
  jenkins_home:

networks:
  ginchat_net:
    driver: bridge
